# Generated by Django 5.0.4 on 2025-12-07 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('cidade_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_cidade',
            },
        ),
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('conteudo_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('corpo', models.TextField()),
                ('detalhes', models.CharField(max_length=255)),
                ('icons', models.TextField(default='icons')),
            ],
            options={
                'db_table': 'tbl_conteudo',
            },
        ),
        migrations.CreateModel(
            name='Designacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_designacao',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('pais_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=4)),
                ('bandeira', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_pais',
            },
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parceiro', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('x_profile', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_parceiros',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('servico_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('corpo', models.TextField()),
                ('detalhes', models.CharField(max_length=255)),
                ('icons', models.TextField(default='icons')),
            ],
            options={
                'db_table': 'tbl_servico',
            },
        ),
        migrations.CreateModel(
            name='Listagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='listimages/')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('endereco', models.TextField()),
                ('descricao', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cidade', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.cidade')),
                ('designacao', models.ForeignKey(blank=True, db_column='designacao_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='leruimoveis.designacao')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.pais')),
            ],
            options={
                'db_table': 'tbl_listagem',
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.pais'),
        ),
    ]
