# Generated by Django 5.0.4 on 2025-12-21 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfraInterna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('infra_interna', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_infra_interna',
            },
        ),
        migrations.AlterField(
            model_name='listagem',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.cidade'),
        ),
    ]
