# Generated by Django 5.0.4 on 2025-12-24 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0002_infrainterna_alter_listagem_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicoesPagamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('condicoes_pagamento', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_condicoes_pagamento',
            },
        ),
        migrations.CreateModel(
            name='EstadoConservacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_conservacao', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_estado_conservacao',
            },
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('piso', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_piso',
            },
        ),
        migrations.CreateModel(
            name='TaxasAdicionais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taxas_adicionais', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_taxas_adicionais',
            },
        ),
        migrations.CreateModel(
            name='CaracteristicasGerais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_util', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('numero_quartos', models.IntegerField(blank=True, null=True)),
                ('numero_suites', models.IntegerField(blank=True, null=True)),
                ('numero_casas_banho', models.IntegerField(blank=True, null=True)),
                ('numero_salas', models.IntegerField(blank=True, null=True)),
                ('numero_cozinhas', models.IntegerField(blank=True, null=True)),
                ('numero_vagas_estacionamento', models.IntegerField(blank=True, null=True)),
                ('ano_construcao', models.IntegerField(blank=True, null=True)),
                ('fk_listagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.listagem')),
                ('fk_condicoes_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.condicoespagamento')),
                ('fk_estado_conservacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.estadoconservacao')),
                ('fk_piso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.piso')),
                ('fk_taxas_adicionais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.taxasadicionais')),
            ],
            options={
                'db_table': 'tbl_caracteristicas_gerais',
            },
        ),
    ]
