# Generated by Django 5.0.4 on 2025-12-26 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0003_condicoespagamento_estadoconservacao_piso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfraExterno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('infra_externo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_infra_externo',
            },
        ),
        migrations.CreateModel(
            name='InfraExternoCaracte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('infra_externo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.infraexterno')),
                ('listagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.listagem')),
            ],
            options={
                'db_table': 'tbl_infra_externo_caracte',
            },
        ),
    ]
