# Generated by Django 5.0.4 on 2025-12-26 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0004_infraexterno_infraexternocaracte'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfraInternaCaracte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('infra_interna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.infrainterna')),
                ('listagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.listagem')),
            ],
            options={
                'db_table': 'tbl_infra_interna_caracte',
            },
        ),
    ]
