# Generated by Django 5.0.4 on 2025-12-26 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0005_infrainternacaracte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComodidadesSeguranca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comodidades_seguranca', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_comodidades_seguranca',
            },
        ),
        migrations.CreateModel(
            name='ComodidadesSegurancaCaracte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comodidades_seguranca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.comodidadesseguranca')),
                ('listagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.listagem')),
            ],
            options={
                'db_table': 'tbl_comodidades_seguranca_caracte',
            },
        ),
    ]
