# Generated by Django 5.0.4 on 2025-12-26 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0006_comodidadesseguranca_comodidadessegurancacaracte'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalizacaoAcessos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('localizacao_acessos', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_localizacao_acessos',
            },
        ),
        migrations.CreateModel(
            name='LocalizacaoAcessosCaracte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fk_localizacao_acessos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.localizacaoacessos')),
                ('listagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.listagem')),
            ],
            options={
                'db_table': 'tbl_localizacao_acessos_caracte',
            },
        ),
    ]
