# Generated by Django 5.0.4 on 2025-12-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0007_localizacaoacessos_localizacaoacessoscaracte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comodidadessegurancacaracte',
            old_name='comodidades_seguranca',
            new_name='fk_comodidades_seguranca',
        ),
    ]
