# Generated by Django 5.0.4 on 2025-12-26 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0008_rename_comodidades_seguranca_comodidadessegurancacaracte_fk_comodidades_seguranca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comodidadessegurancacaracte',
            old_name='listagem',
            new_name='fk_listagem',
        ),
        migrations.RenameField(
            model_name='infraexternocaracte',
            old_name='infra_externo',
            new_name='fk_infra_externo',
        ),
        migrations.RenameField(
            model_name='infraexternocaracte',
            old_name='listagem',
            new_name='fk_listagem',
        ),
        migrations.RenameField(
            model_name='infrainternacaracte',
            old_name='infra_interna',
            new_name='fk_infra_interna',
        ),
        migrations.RenameField(
            model_name='infrainternacaracte',
            old_name='listagem',
            new_name='fk_listagem',
        ),
        migrations.RenameField(
            model_name='localizacaoacessoscaracte',
            old_name='listagem',
            new_name='fk_listagem',
        ),
    ]
