# Generated by Django 5.0.4 on 2025-12-26 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0009_rename_listagem_comodidadessegurancacaracte_fk_listagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituacaoLegal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('situacao_legal', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_situacao_legal',
            },
        ),
        migrations.CreateModel(
            name='SituacaoLegalCaracte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fk_listagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.listagem')),
                ('fk_situacao_legal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.situacaolegal')),
            ],
            options={
                'db_table': 'tbl_situacao_legal_caracte',
            },
        ),
    ]
