# Generated by Django 5.0.4 on 2026-02-01 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0010_situacaolegal_situacaolegalcaracte'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotosAdicionais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='listimages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fk_listagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.listagem')),
            ],
            options={
                'db_table': 'tbl_fotos_adicionais',
            },
        ),
    ]
