# Generated by Django 5.0.4 on 2026-02-05 22:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0011_fotosadicionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotosadicionais',
            name='descricao',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
