# Generated by Django 5.0.4 on 2026-02-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0012_fotosadicionais_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoParceiro',
            fields=[
                ('tip_parceiro_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_parceiro', models.CharField(default='Essencial', max_length=100)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_parceiros_tipo',
            },
        ),
        migrations.DeleteModel(
            name='Parceiro',
        ),
    ]
