# Generated by Django 5.0.4 on 2026-02-16 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0013_tipoparceiro_delete_parceiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('parceiro_id', models.AutoField(primary_key=True, serialize=False)),
                ('parceiro', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=13)),
                ('telefone_alternativo', models.CharField(max_length=13)),
                ('site', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('tipo_imobiliaria', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('sobre_parceiro', models.TextField()),
                ('data_registro', models.DateField(auto_now=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('fk_tipo_parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.tipoparceiro')),
            ],
            options={
                'db_table': 'tbl_parceiros',
            },
        ),
        migrations.CreateModel(
            name='ParceirosSocialMedia',
            fields=[
                ('parceiros_social_media_id', models.AutoField(primary_key=True, serialize=False)),
                ('social_media', models.CharField(max_length=50)),
                ('social_media_icon', models.TextField(default='icons')),
                ('social_media_link', models.URLField(blank=True, null=True)),
                ('fk_parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.parceiro')),
            ],
            options={
                'db_table': 'tb_parceiros_social_media',
            },
        ),
    ]
