# Generated by Django 5.0.4 on 2026-02-16 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0014_parceiro_parceirossocialmedia'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parceirossocialmedia',
            table='tbl_parceiros_social_media',
        ),
    ]
