# Generated by Django 5.0.4 on 2026-03-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0015_alter_parceirossocialmedia_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('tipo_cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cliente', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'tbl_tipo_cliente',
            },
        ),
    ]
