# Generated by Django 5.0.4 on 2026-03-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0016_tipocliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('tipo_servico_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_servico', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_tipo_servico',
            },
        ),
    ]
