# Generated by Django 5.0.4 on 2026-03-12 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0017_tiposervico'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPlano',
            fields=[
                ('tipo_plano_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_plano', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('fk_tipo_cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.tipocliente')),
                ('fk_tipo_servico', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.tiposervico')),
            ],
            options={
                'db_table': 'tbl_tipo_plano',
            },
        ),
    ]
