# Generated by Django 5.0.4 on 2026-03-13 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0018_tipoplano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoplano',
            name='fk_tipo_cliente',
        ),
        migrations.RemoveField(
            model_name='tipoplano',
            name='fk_tipo_servico',
        ),
    ]
