# Generated by Django 5.0.4 on 2026-03-13 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0019_remove_tipoplano_fk_tipo_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoplano',
            name='tipo_cliente_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.tipocliente'),
        ),
    ]
