# Generated by Django 5.0.4 on 2026-03-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0020_tipoplano_tipo_cliente_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoplano',
            old_name='tipo_cliente_id',
            new_name='fk_tipo_cliente',
        ),
    ]
