# Generated by Django 5.0.4 on 2026-03-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0021_rename_tipo_cliente_id_tipoplano_fk_tipo_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('plano_id', models.AutoField(primary_key=True, serialize=False)),
                ('plano', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_plano',
            },
        ),
        migrations.CreateModel(
            name='TipoNegocio',
            fields=[
                ('tipo_negocio_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_negocio', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipo_negocio',
            },
        ),
    ]
