# Generated by Django 5.0.4 on 2026-03-13 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0022_plano_tiponegocio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='plano',
        ),
        migrations.AddField(
            model_name='plano',
            name='fk_tipo_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.tipocliente'),
        ),
        migrations.AddField(
            model_name='plano',
            name='fk_tipo_servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.tiposervico'),
        ),
        migrations.AddField(
            model_name='plano',
            name='numero_listagens',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plano',
            name='periodo',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plano',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='plano',
            name='tipo_negocio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.tiponegocio'),
        ),
        migrations.AddField(
            model_name='plano',
            name='tipo_plano',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.tipoplano'),
        ),
        migrations.AddField(
            model_name='plano',
            name='total_empreendimentos',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
