# Generated by Django 5.0.4 on 2026-03-13 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0023_remove_plano_plano_plano_fk_tipo_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tiponegocio',
            table='tbl_tipo_negocio',
        ),
    ]
