# Generated by Django 5.0.4 on 2026-03-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0024_alter_tiponegocio_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalhesImovel',
            fields=[
                ('detalhes_imovel_id', models.AutoField(primary_key=True, serialize=False)),
                ('detalhes_imovel', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_detalhes_imovel',
            },
        ),
    ]
