# Generated by Django 5.0.4 on 2026-03-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0025_detalhesimovel'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='numero_foto',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
