# Generated by Django 5.0.4 on 2026-03-15 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0026_plano_numero_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='detalhes_imovel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.detalhesimovel'),
        ),
    ]
