# Generated by Django 5.0.4 on 2026-04-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0027_plano_detalhes_imovel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('configuracoes_id', models.AutoField(primary_key=True, serialize=False)),
                ('publicidade', models.IntegerField(blank=True, choices=[(0, 'Desativado'), (1, 'Ativado')], default=0, null=True)),
            ],
            options={
                'db_table': 'tbl_configuracoes',
            },
        ),
    ]
