# Generated by Django 5.0.4 on 2026-04-20 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0029_configuracoes_ce_utilizador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('favorito_id', models.AutoField(primary_key=True, serialize=False)),
                ('listage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.listagem')),
                ('utilizador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_favorito',
            },
        ),
    ]
