# Generated by Django 5.0.4 on 2026-04-20 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0030_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorito',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
