# Generated by Django 5.0.4 on 2026-04-20 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0031_favorito_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorito',
            old_name='listage_id',
            new_name='listagem',
        ),
    ]
