# Generated by Django 5.0.4 on 2026-04-20 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0032_rename_listage_id_favorito_listagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorito',
            old_name='utilizador_id',
            new_name='utilizador',
        ),
    ]
