# Generated by Django 5.0.4 on 2026-04-25 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0034_listagem_utilizador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUserProfile',
            fields=[
                ('authUserProfile', models.AutoField(primary_key=True, serialize=False)),
                ('primeiro_nome', models.CharField(max_length=50)),
                ('sobre_nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_user_profile',
            },
        ),
    ]
