# Generated by Django 5.0.4 on 2026-04-26 15:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0035_authuserprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoAprovado',
            fields=[
                ('plano_activo_id', models.AutoField(primary_key=True, serialize=False)),
                ('agencia_id', models.IntegerField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_aprovados', to='leruimoveis.plano')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_planos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano Aprovado',
                'verbose_name_plural': 'Planos Aprovados',
                'db_table': 'tbl_plano_aprovado',
                'unique_together': {('plano', 'utilizador')},
            },
        ),
    ]
