# Generated by Django 5.0.4 on 2026-04-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0036_planoaprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuserprofile',
            name='foto_utilizador',
            field=models.ImageField(blank=True, null=True, upload_to='utilizadores/'),
        ),
    ]
