# Generated by Django 5.0.4 on 2026-05-03 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0037_authuserprofile_foto_utilizador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoDenuncia',
            fields=[
                ('id_motivo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_motivo_denuncia',
            },
        ),
        migrations.AddField(
            model_name='authuserprofile',
            name='sobreMim',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='DenunciaEfetuada',
            fields=[
                ('id_denuncia', models.AutoField(primary_key=True, serialize=False)),
                ('outros_detalhes', models.TextField(blank=True, max_length=500, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor_denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_enviadas', to=settings.AUTH_USER_MODEL)),
                ('perfil_denunciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_recebidas', to=settings.AUTH_USER_MODEL)),
                ('ce_motivos', models.ManyToManyField(related_name='denuncias', to='leruimoveis.motivodenuncia')),
            ],
            options={
                'db_table': 'tbl_denuncia_efetuada',
            },
        ),
        migrations.CreateModel(
            name='HistoricoLogin',
            fields=[
                ('historico_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_login', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('foi_sucesso', models.BooleanField(default=True)),
                ('ce_utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_acessos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Login',
                'verbose_name_plural': 'Históricos de Login',
                'db_table': 'tbl_historico_login',
                'ordering': ['-data_login'],
            },
        ),
        migrations.CreateModel(
            name='DenunciaEfetuadaMotivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('denuncia_efectuada_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.denunciaefetuada')),
                ('motivo_denuncia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leruimoveis.motivodenuncia')),
            ],
            options={
                'db_table': 'tbl_denuncia_efetuada_motivo',
            },
        ),
        migrations.CreateModel(
            name='FavoritosPerfil',
            fields=[
                ('favorito_perfil_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ce_agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritado_por', to=settings.AUTH_USER_MODEL)),
                ('ce_utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_favorito_perfil',
                'unique_together': {('ce_utilizador', 'ce_agente')},
            },
        ),
    ]
