# Generated by Django 5.0.4 on 2026-05-04 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0038_motivodenuncia_authuserprofile_sobremim_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denunciaefetuadamotivo',
            old_name='denuncia_efectuada_id',
            new_name='ce_denuncia_efectuada',
        ),
        migrations.RenameField(
            model_name='denunciaefetuadamotivo',
            old_name='motivo_denuncia_id',
            new_name='ce_motivo_denuncia',
        ),
    ]
