# Generated by Django 5.0.4 on 2026-05-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0039_rename_denuncia_efectuada_id_denunciaefetuadamotivo_ce_denuncia_efectuada_and_more'),
    ]

    operations = [
        # 1. Safely drop the M2M table if it exists
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS `tbl_denuncia_efetuada_ce_motivos`;",
            reverse_sql=migrations.RunSQL.noop,
        ),

        # 2. Update Django state without touching DB
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='denunciaefetuada',
                    name='ce_motivos',
                ),
            ],
        ),

        # 3. Add the correct M2M field
        migrations.AddField(
            model_name='denunciaefetuada',
            name='ce_motivos',
            field=models.ManyToManyField(to='leruimoveis.MotivoDenuncia', related_name='denuncias', blank=True),
        ),
    ]
