# Generated by Django 5.0.4 on 2026-05-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0040_alter_denunciaefetuada_ce_motivos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listagem',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
