# Generated by Django 5.0.4 on 2026-06-27 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0041_alter_listagem_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('agencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('agencia', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
                ('telefone_alternativo', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('endereco', models.CharField(max_length=100)),
                ('matriz', models.ForeignKey(blank=True, help_text='Deixe em branco se esta agência for a matriz.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filiais', to='leruimoveis.agencia', verbose_name='Matriz')),
            ],
            options={
                'db_table': 'tbl_agencia',
            },
        ),
    ]
