# Generated by Django 5.0.4 on 2026-07-04 01:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0043_agencia_ce_utilizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencia',
            name='agencia_missao',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(500)]),
        ),
        migrations.AddField(
            model_name='agencia',
            name='agencia_objectivo',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(500)]),
        ),
        migrations.AddField(
            model_name='agencia',
            name='agencia_visao',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(500)]),
        ),
        migrations.AddField(
            model_name='agencia',
            name='logotipo',
            field=models.ImageField(blank=True, null=True, upload_to='logotipos/'),
        ),
        migrations.AddField(
            model_name='agencia',
            name='sobre_agencia',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(500)]),
        ),
    ]
