# Generated by Django 5.0.4 on 2026-07-05 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leruimoveis', '0044_agencia_agencia_missao_agencia_agencia_objectivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenciaUtilizador',
            fields=[
                ('agencia_utilizador_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ce_filia_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilizadores', to='leruimoveis.agencia')),
                ('ce_utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencia_utilizadores', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criados_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_agencia_utilizador',
            },
        ),
    ]
